server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/Documents/Databases/fiapdatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl