create table tbBook(
    id bigint generated by default as identity,
    title varchar(100),
    description varchar(255),
    price decimal(19,2),
    isbn varchar(20),
    publicationDate timestamp,
    primary key (id)
)
